CREATE TABLE properties (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    tour_url TEXT NOT NULL,
    user_id INT(11) UNSIGNED NOT NULL,
    property_type_id INT(11) UNSIGNED NOT NULL,
    price_usd INT(11) UNSIGNED,
    price_gs INT(11) UNSIGNED,
    rooms INT UNSIGNED,
    bathrooms INT UNSIGNED,
    thumbnail VARCHAR(255),
    lat DECIMAL(10, 7),
    lng DECIMAL(10, 7),
    department VARCHAR(255),
    city VARCHAR(255),
    neighborhood VARCHAR(255),
    code_ref VARCHAR(100),
    land_m2 INT(11) UNSIGNED,
    land_width INT(11) UNSIGNED,
    land_length INT(11) UNSIGNED,
    build_m2 INT UNSIGNED,
    year INT UNSIGNED,
    parking_capacity INT UNSIGNED,
    building_floors INT UNSIGNED,
    expiration_date DATE,
    status ENUM('publicado', 'borrador') NOT NULL DEFAULT 'borrador',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Foreign Key
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (property_type_id) REFERENCES property_types(id)
);