CREATE TABLE properties (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    price DECIMAL(15,2) NOT NULL,
    rooms INT UNSIGNED,
    bathroom INT UNSIGNED,
    tour_url TEXT,
    user_id INT(11) UNSIGNED,
    location VARCHAR(255),
    code_ref VARCHAR(100),
    land_dimensions VARCHAR(50),
    build_m2 INT UNSIGNED,
    year INT,
    parking_capacity INT UNSIGNED,
    building_floors INT UNSIGNED,
    has_terrace BOOLEAN DEFAULT FALSE,
    has_balcony BOOLEAN DEFAULT FALSE,
    has_bathroom_furniture BOOLEAN DEFAULT FALSE,
    has_kitchen_furniture BOOLEAN DEFAULT FALSE,
    has_pool BOOLEAN DEFAULT FALSE,
    has_barbecue BOOLEAN DEFAULT FALSE,
    has_ac BOOLEAN DEFAULT FALSE,
    property_type ENUM('casa', 'duplex', 'departamento', 'monoambiente') NOT NULL DEFAULT 'casa',
    status ENUM('publicado', 'borrador') NOT NULL DEFAULT 'borrador',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Foreign Key
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
